# Generated by Django 5.2.1 on 2025-05-14 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0)),
                ('final_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eng_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('skill_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequential_number', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teaching_days', models.IntegerField(default=0)),
                ('absence_days', models.IntegerField(default=0)),
                ('received_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_teaching_days', models.IntegerField(default=0)),
                ('extra_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_support', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('responsibility_support', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakfast_support', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('skill_sessions', models.IntegerField(default=0)),
                ('skill_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('english_sessions', models.IntegerField(default=0)),
                ('english_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_students_list', models.TextField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
