# Generated by Django 5.2.1 on 2025-05-15 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='student',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base tuition fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, help_text='Classroom assignment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when record was created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount_percentage',
            field=models.FloatField(default=0, help_text='Discount percentage applied to base fee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='eng_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='English class fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='facility_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Facility usage fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='final_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final fee after discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='meal_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meal fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the student', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='pm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parent-Management fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='pt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parent-Teacher fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount to be paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='sequential_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID for API lookups', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Skill class fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_fund',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Student fund contribution', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(help_text='Unique identifier for the student', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee including all components', max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when record was last updated'),
        ),
        migrations.AlterField(
            model_name='student',
            name='utilities_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional utilities fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='absence_days',
            field=models.IntegerField(default=0, help_text='Number of absence days'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base monthly salary', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='breakfast_support',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Breakfast allowance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when record was created'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='english_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment for English teaching', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='english_sessions',
            field=models.IntegerField(default=0, help_text='Number of English sessions taught'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='extra_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra payment for additional work', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='extra_teaching_days',
            field=models.IntegerField(default=0, help_text='Number of extra teaching days'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the teacher', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='insurance_support',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Insurance support amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='Full name of the teacher', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='new_students_list',
            field=models.TextField(blank=True, help_text='List of new students recruited', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='received_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary after absence deductions', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='responsibility_support',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional payment for responsibilities', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(help_text='Role or position (e.g., Head Teacher, Assistant)', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skill_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment for skill teaching', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skill_sessions',
            field=models.IntegerField(default=0, help_text='Number of skill sessions taught'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_days',
            field=models.IntegerField(default=0, help_text='Number of teaching days in the month'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total salary including all components', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account associated with this teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
