# Generated by Django 5.2.1 on 2025-05-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
