name: Build and Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/docker-build.yml'
      - 'docker-compose.yml'
      - 'nginx/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/docker-build.yml'

env:
  REGISTRY: docker.io
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/monkids-backend
  # Database Configuration
  DATABASE_HOST: 172.31.14.122
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: postgres
  # JWT Configuration
  JWT_SECRET: monkids
  JWT_REFRESH_SECRET: monkids
  JWT_EXPIRATION: 1d
  JWT_REFRESH_EXPIRATION: 7d
  # Google OAuth2 Configuration
  GOOGLE_CLIENT_ID: 542269964324-6kmatcq5rp191efr3eiouu60hkqdg6jk.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CALLBACK_URL: https://api.monkids.site/api/auth/google/callback
  # Application Configuration
  PORT: 8000
  NODE_ENV: production
  FRONTEND_URL: https://www.monkids.site/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-,format=short
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Configure SSH
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.key
          chmod 600 ~/.ssh/ec2.key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USERNAME }}
            IdentityFile ~/.ssh/ec2.key
            StrictHostKeyChecking no
          END

      - name: Copy configuration files to EC2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          scp backend/docker-compose.yml ec2:~/monkid_management/
          scp -r nginx ec2:~/monkid_management/

      - name: Deploy with Docker Compose
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ssh ec2 "
          cd ~/monkid_management
          
          # Create .env file with required environment variables
          cat > .env << EOL
          # Database Configuration
          DATABASE_HOST=${{ env.DATABASE_HOST }}
          DATABASE_PORT=${{ env.DATABASE_PORT }}
          DATABASE_USERNAME=${{ env.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }}
          DATABASE_NAME=${{ env.DATABASE_NAME }}

          # JWT Configuration
          JWT_SECRET=${{ env.JWT_SECRET }}
          JWT_REFRESH_SECRET=${{ env.JWT_REFRESH_SECRET }}
          JWT_EXPIRATION=${{ env.JWT_EXPIRATION }}
          JWT_REFRESH_EXPIRATION=${{ env.JWT_REFRESH_EXPIRATION }}

          # Google OAuth2 Configuration
          GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL=${{ env.GOOGLE_CALLBACK_URL }}

          # Application Configuration
          PORT=${{ env.PORT }}
          NODE_ENV=${{ env.NODE_ENV }}
          FRONTEND_URL=${{ env.FRONTEND_URL }}

          # Docker configuration
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          EOL

          echo 'Stopping existing containers...'
          docker-compose down --remove-orphans

          echo 'Cleaning up Docker system...'
          docker system prune -f
          
          echo 'Setting up directories and permissions...'
          sudo mkdir -p /etc/letsencrypt
          sudo chown -R $USER:$USER /etc/letsencrypt
          
          echo 'Pulling new images...'
          docker-compose pull
          
          echo 'Starting backend container...'
          docker-compose up -d backend
          
          echo 'Waiting for backend startup...'
          sleep 10
          
          echo '=== Fix Puppeteer Permissions ==='
          docker exec monkids_backend sh -c '
            mkdir -p /home/pptruser/.local/share/applications
            mkdir -p /home/pptruser/.cache/{fontconfig,puppeteer}
            mkdir -p /home/pptruser/.config
            chown -R pptruser:pptruser /home/pptruser
            chmod -R 755 /home/pptruser
          '
          
          echo '=== Backend Container Status ==='
          docker ps -a | grep backend
          
          echo '=== Backend Container Logs ==='
          docker logs monkids_backend --tail 100
          
          echo '=== Testing Backend API ==='
          curl -v http://localhost:8000/api/health || true
          
          echo '=== Starting Nginx ==='
          docker-compose up -d nginx
          
          echo '=== Nginx Status ==='
          docker ps -a | grep nginx
          docker logs nginx
          
          echo '=== Network Status ==='
          netstat -tulpn | grep -E ':(80|443|8000)' || true
          "

      - name: Health check
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          MAX_RETRIES=3
          RETRY_COUNT=0
          WAIT_TIME=20

          echo "Starting health check..."
          until ssh ec2 "
            echo '=== Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES ==='
            
            echo '=== Container Status ==='
            docker ps -a
            
            echo '=== Backend Container Logs ==='
            docker logs monkids_backend --tail 50
            
            echo '=== Nginx Container Logs ==='
            docker logs nginx
            
            echo '=== Testing Backend API ==='
            curl -v http://localhost:8000/api/health
            curl -v https://api.monkids.site/api/health || true
            
            echo '=== Network Status ==='
            netstat -tulpn | grep -E ':(80|443|8000)'
          " || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
            echo "Health check failed. Waiting $WAIT_TIME seconds before retry..."
            sleep $WAIT_TIME
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          
          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
            echo "Health check failed after $MAX_RETRIES attempts"
            exit 1
          fi 